"""windMindOM workflow schemas — pydantic request / response（WMOM-20260504-17 / -18 / -20260509-03 / -04）。"""

from .signoff_schemas import (
    ApprovalResultResponse,
    ApproveStepRequest,
    PendingSignoffItem,
    PendingSignoffListResponse,
    RejectStepRequest,
    SignoffChainResponse,
    SignoffStepResponse,
)
from .work_order_schemas import (
    CancelRequest,
    CreateWorkOrderRequest,
    DispatchRequest,
    FinishRequest,
    ProgressNoteResponse,
    RejectRequest,
    ReopenRequest,
    StartWorkRequest,
    UpdateProgressRequest,
    WorkOrderListResponse,
    WorkOrderResponse,
)
from .material_request_schemas import (
    CancelMaterialRequest,
    CloseMaterialRequest,
    CreateMaterialRequest,
    CreateMaterialRequestItem,
    CreateMaterialReturn,
    DispatchMaterialRequest,
    MaterialRequestItemResponse,
    MaterialRequestListResponse,
    MaterialRequestResponse,
    MaterialReturnResponse,
    ReceiveMaterialRequest,
    SubmitForApprovalRequest,
)
from .inventory_schemas import (
    AdjustInventoryRequest,
    AdjustInventoryResult,
    AdjustmentLogListResponse,
    AdjustmentLogResponse,
    CreateInventoryItemRequest,
    CreateWarehouseRequest,
    InventoryItemListResponse,
    InventoryItemResponse,
    UpdateInventoryMetadataRequest,
    WarehouseListResponse,
    WarehouseResponse,
)
from .inspection_schemas import (
    CreateInspectionScheduleRequest,
    InspectionScheduleListResponse,
    InspectionScheduleResponse,
    RunSchedulerResponse,
    SpawnedInspectionResponse,
    UpdateInspectionScheduleRequest,
)

__all__ = [
    # signoff
    "ApprovalResultResponse",
    "ApproveStepRequest",
    "PendingSignoffItem",
    "PendingSignoffListResponse",
    "RejectStepRequest",
    "SignoffChainResponse",
    "SignoffStepResponse",
    # work order
    "CancelRequest",
    "CreateWorkOrderRequest",
    "DispatchRequest",
    "FinishRequest",
    "ProgressNoteResponse",
    "RejectRequest",
    "ReopenRequest",
    "StartWorkRequest",
    "UpdateProgressRequest",
    "WorkOrderListResponse",
    "WorkOrderResponse",
    # material request (WMOM-20260509-03)
    "CancelMaterialRequest",
    "CloseMaterialRequest",
    "CreateMaterialRequest",
    "CreateMaterialRequestItem",
    "CreateMaterialReturn",
    "DispatchMaterialRequest",
    "MaterialRequestItemResponse",
    "MaterialRequestListResponse",
    "MaterialRequestResponse",
    "MaterialReturnResponse",
    "ReceiveMaterialRequest",
    "SubmitForApprovalRequest",
    # inventory (WMOM-20260509-04)
    "AdjustInventoryRequest",
    "AdjustInventoryResult",
    "AdjustmentLogListResponse",
    "AdjustmentLogResponse",
    "CreateInventoryItemRequest",
    "CreateWarehouseRequest",
    "InventoryItemListResponse",
    "InventoryItemResponse",
    "UpdateInventoryMetadataRequest",
    "WarehouseListResponse",
    "WarehouseResponse",
    # inspection schedule (WMOM-20260505-22)
    "CreateInspectionScheduleRequest",
    "InspectionScheduleListResponse",
    "InspectionScheduleResponse",
    "RunSchedulerResponse",
    "SpawnedInspectionResponse",
    "UpdateInspectionScheduleRequest",
]
